pipeline {
    agent { docker { image 'node:8.15-jessie' } }
    stages {
        stage('build') {
            steps {
              sh 'yarn install --production=true'
              sh 'yarn build'
              sh './jenkins/scripts/deliver.sh'
              input message: 'Finished serving the web site? (Click "Proceed" to continue)'
              sh './jenkins/scripts/kill.sh'
            }
        }
    }
}
