pipeline {
    agent {
      docker {
        image 'node:8.15-jessie'
        args '-p 8000:8000'
      }
    }
    environment {
        CI = 'true'
        SERVER_PORT: 8000
    }
    stages {
        stage('build') {
            steps {
              sh 'yarn install --production=true'
              sh 'yarn build'
            }
        }
        stage('deploy') {
            steps {
              sh './jenkins/scripts/deliver.sh'
              input message: 'Finished serving the web site? (Click "Proceed" to continue)'
              sh './jenkins/scripts/kill.sh'
            }
        }
    }
}
